local MEAT = "KitchenConsolidation.MeatPieces"
local FISH = "KitchenConsolidation.FishPieces"

local PREPMAP = {
    -- Meat Items
    ["Base.Bacon"] = MEAT,
    ["Base.BaconRashers"] = MEAT,
    ["Base.Baloney"] = MEAT,
    ["Base.BaloneySlice"] = MEAT,
    ["Base.Beef"] = MEAT,
    ["Base.BeefJerky"] = MEAT,
    ["Base.MeatPatty"] = MEAT,
    ["Base.ChickenWhole"] = MEAT,
    ["Base.ChickenFillet"] = MEAT,
    ["Base.Chicken"] = MEAT,
    ["Base.ChickenNuggets"] = MEAT,
    ["Base.ChickenWings"] = MEAT,
    ["Base.MincedMeat"] = MEAT,
    ["Base.Ham"] = MEAT,
    ["Base.HamSlice"] = MEAT,
    ["Base.Hotdog_single"] = MEAT,
    ["Base.MuttonChop"] = MEAT,
    ["Base.HotdogPack"] = MEAT,
    ["Base.Pepperoni"] = MEAT,
    ["Base.Pork"] = MEAT,
    ["Base.PorkChop"] = MEAT,
    ["Base.Salami"] = MEAT,
    ["Base.SalamiSlice"] = MEAT,
    ["Base.Sausage"] = MEAT,
    ["Base.Steak"] = MEAT,
    ["Base.TurkeyWhole"] = MEAT,
    ["Base.TurkeyFillet"] = MEAT,
    ["Base.TurkeyLegs"] = MEAT,
    ["Base.TurkeyWings"] = MEAT,
    ["Base.Venison"] = MEAT,
    ["Base.Rabbitmeat"] = MEAT,
    ["Base.Smallbirdmeat"] = MEAT,
    ["Base.Smallanimalmeat"] = MEAT,
    ["Base.FrogMeat"] = MEAT,
    -- Fish Items
    ["Base.FishFillet"] = FISH,
    ["Base.SmallFishFillet"] = FISH,
    -- Vegetable items
    ["Base.Avocado"] = "KitchenConsolidation.AvocadoPieces",
    ["Base.BellPepper"] = "KitchenConsolidation.BellPepperPieces",
    ["Base.Celery"] = "KitchenConsolidation.CeleryPieces",
    ["Base.Cucumber"] = "KitchenConsolidation.CucumberPieces",
    ["Base.Broccoli"] = "KitchenConsolidation.BroccoliPieces",
    ["Base.Carrots"] = "KitchenConsolidation.CarrotPieces",
    ["Base.Corn"] = "KitchenConsolidation.CornPieces",
    ["Base.Daikon"] = "KitchenConsolidation.DaikonPieces",
    ["Base.Eggplant"] = "KitchenConsolidation.EggplantPieces",
    ["Base.PepperHabanero"] = "KitchenConsolidation.PepperHabaneroPieces",
    ["Base.PepperJalapeno"] = "KitchenConsolidation.PepperJalapenoPieces",
    ["Base.Leek"] = "KitchenConsolidation.LeekPieces",
    ["Base.Lettuce"] = "KitchenConsolidation.LettucePieces",
    ["Base.MushroomGeneric1"] = "KitchenConsolidation.MushroomGenericPieces",
    ["Base.MushroomGeneric2"] = "KitchenConsolidation.MushroomGenericPieces",
    ["Base.MushroomGeneric3"] = "KitchenConsolidation.MushroomGenericPieces",
    ["Base.MushroomGeneric4"] = "KitchenConsolidation.MushroomGenericPieces",
    ["Base.MushroomGeneric5"] = "KitchenConsolidation.MushroomGenericPieces",
    ["Base.MushroomGeneric6"] = "KitchenConsolidation.MushroomGenericPieces",
    ["Base.MushroomGeneric7"] = "KitchenConsolidation.MushroomGenericPieces",
    ["Base.Onion"] = "KitchenConsolidation.OnionPieces",
    ["Base.Seaweed"] = "KitchenConsolidation.SeaweedPieces",
    ["Base.Zucchini"] = "KitchenConsolidation.ZucchiniPieces",
    ["farming.Cabbage"] = "KitchenConsolidation.CabbagePieces",
    ["farming.Potato"] = "KitchenConsolidation.PotatoPieces",
    ["farming.RedRadish"] = "KitchenConsolidation.RedRadishPieces",
    ["farming.Tomato"] = "KitchenConsolidation.TomatoPieces",
    ["Base.Tofu"] = "KitchenConsolidation.TofuPieces",
}

return PREPMAP